<?php
/**
 * Auto Tirage - Version Multi-Session
 * Refactorisée pour utiliser le système sessions global
 */
?>
<style>
    .main-container {
        background: white;
        border-radius: 15px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        margin: 1rem auto;
        overflow: hidden;
    }

    .header-section {
        background: linear-gradient(135deg, #e3f2fd 0%, #f3e5f5 100%);
        color: #424242;
        padding: 1.5rem;
        text-align: center;
        border-bottom: 1px solid #e0e0e0;
    }

    .header-section h1 {
        margin: 0;
        font-weight: 400;
        font-size: 2.2rem;
        color: #616161;
    }

    .session-control-bar {
        background: #f5f5f5;
        border-bottom: 1px solid #e0e0e0;
        padding: 1rem 1.5rem;
    }

    .session-card {
        background: white;
        border: 2px solid #e0e0e0;
        border-radius: 8px;
        padding: 0.75rem;
        margin-bottom: 0.5rem;
        cursor: pointer;
        transition: all 0.2s;
    }

    .session-card.active {
        border-color: #4caf50;
        background: #f1f8e9;
    }

    .session-card:hover {
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

    .form-section {
        padding: 1.5rem;
    }

    .btn-modern {
        border-radius: 8px;
        padding: 0.5rem 1rem;
        font-weight: 500;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-xl-10">
            <div class="main-container">
                <!-- Header -->
                <div class="header-section">
                    <h1><i class="fa fa-magic"></i> Auto Tirage Multi-Session</h1>
                    <p>Gestion des impressions par contact</p>
                </div>

                <!-- Session Control Bar -->
                <div class="session-control-bar">
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <label><strong>Session active :</strong></label>
                            <select id="session-selector" class="form-control" onchange="switchToSelectedSession()">
                                <option value="">-- Aucune session --</option>
                            </select>
                        </div>
                        <div class="col-md-6 text-right">
                            <button class="btn btn-success btn-modern" onclick="showCreateSessionModal()">
                                <i class="fa fa-plus"></i> Nouvelle Session
                            </button>
                            <button id="close-session-btn" class="btn btn-danger btn-modern"
                                onclick="closeCurrentSession()" style="display:none;">
                                <i class="fa fa-times"></i> Fermer Session
                            </button>
                        </div>
                    </div>

                    <!-- Sessions Quick View -->
                    <div id="sessions-quick-view" class="mt-3" style="display:none;">
                        <small class="text-muted">Sessions actives:</small>
                        <div id="sessions-list" class="mt-2">
                            <!-- Generated by JS -->
                        </div>
                    </div>
                </div>

                <!-- Main Content -->
                <div class="form-section">
                    <!-- No Session Selected -->
                    <div id="no-session-view" class="text-center py-5">
                        <i class="fa fa-users fa-4x text-muted mb-3"></i>
                        <h4>Aucune session active</h4>
                        <p class="text-muted">Créez ou sélectionnez une session pour commencer</p>
                    </div>

                    <!-- Session Active View -->
                    <div id="session-view" style="display:none;">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4>Jobs de : <span id="current-session-name" class="text-primary"></span></h4>
                            <div>
                                <span class="badge badge-info">
                                    <i class="fa fa-list"></i> <span id="job-count">0</span> jobs
                                </span>
                                <span class="badge badge-success">
                                    <i class="fa fa-euro"></i> <span id="session-total">0.00</span> €
                                </span>
                            </div>
                        </div>

                        <!-- Jobs Table -->
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Machine</th>
                                        <th>Document</th>
                                        <th>Détails</th>
                                        <th>Papier</th>
                                        <th>Encre</th>
                                        <th>Prix Total</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="jobs-tbody">
                                    <!-- Generated by JS -->
                                </tbody>
                                <tfoot>
                                    <tr class="table-info">
                                        <td colspan="5" class="text-right"><strong>Total Session :</strong></td>
                                        <td colspan="2"><strong><span id="total-footer">0.00</span> €</strong></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>

                        <div class="text-right mt-3">
                            <button class="btn btn-success btn-lg" onclick="finishAndCloseSession()">
                                <i class="fa fa-check"></i> Terminer & Valider
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Variables globales
    let currentSessionId = null;
    let allSessions = [];
    let sessionJobs = [];

    // Init au chargement
    document.addEventListener('DOMContentLoaded', () => {
        console.log('[AutoTirage] Init multi-session page');
        loadSessions();

        // Écouter les événements du PrintSessionManager global
        window.addEventListener('sessions-loaded', (e) => {
            console.log('[AutoTirage] Sessions loaded event', e.detail);
            refreshSessionsList(e.detail.sessions);
        });

        window.addEventListener('session-switched', (e) => {
            console.log('[AutoTirage] Session switched event', e.detail);
            currentSessionId = e.detail.sessionId;
            loadCurrentSessionJobs();
        });

        window.addEventListener('print-job-registered', (e) => {
            console.log('[AutoTirage] Print job registered', e.detail);
            if (e.detail.sessionId === currentSessionId) {
                loadCurrentSessionJobs();
            }
        });
    });

    // Charger toutes les sessions
    async function loadSessions() {
        try {
            const response = await fetch('?sessions&action=list');
            const data = await response.json();

            allSessions = data.sessions || [];
            refreshSessionsList(allSessions);

            // Restaurer dernière session
            if (window.printSessionManager && window.printSessionManager.currentSessionId) {
                currentSessionId = window.printSessionManager.currentSessionId;
                selectSession(currentSessionId);
            }
        } catch (error) {
            console.error('[AutoTirage] Erreur chargement sessions:', error);
        }
    }

    // Actualiser l'affichage des sessions
    function refreshSessionsList(sessions) {
        allSessions = sessions;

        // Update selector
        const selector = document.getElementById('session-selector');
        selector.innerHTML = '<option value="">-- Aucune session --</option>';

        sessions.forEach(session => {
            const option = document.createElement('option');
            option.value = session.id;
            option.textContent = `${session.contact}${session.session_name ? ' - ' + session.session_name : ''} (${session.job_count} jobs, ${session.total_price.toFixed(2)} €)`;
            selector.appendChild(option);
        });

        // Update quick view
        const quickView = document.getElementById('sessions-quick-view');
        const sessionsList = document.getElementById('sessions-list');

        if (sessions.length > 0) {
            quickView.style.display = 'block';
            sessionsList.innerHTML = '';

            sessions.forEach(session => {
                const card = document.createElement('div');
                card.className = 'session-card' + (session.id === currentSessionId ? ' active' : '');
                card.onclick = () => selectSession(session.id);
                card.innerHTML = `
                <div class="d-flex justify-content-between">
                    <strong>${session.contact}</strong>
                    <span class="text-muted">${session.job_count} jobs - ${session.total_price.toFixed(2)} €</span>
                </div>
            `;
                sessionsList.appendChild(card);
            });
        } else {
            quickView.style.display = 'none';
        }

        // Update current session if selected
        if (currentSessionId) {
            selector.value = currentSessionId;
        }
    }

    // Sélectionner une session
    function selectSession(sessionId) {
        currentSessionId = sessionId;

        if (window.printSessionManager) {
            window.printSessionManager.switchToSession(sessionId);
        }

        document.getElementById('session-selector').value = sessionId;

        if (sessionId) {
            const session = allSessions.find(s => s.id === parseInt(sessionId));
            if (session) {
                document.getElementById('current-session-name').textContent = session.contact;
                document.getElementById('no-session-view').style.display = 'none';
                document.getElementById('session-view').style.display = 'block';
                document.getElementById('close-session-btn').style.display = 'inline-block';

                loadCurrentSessionJobs();
            }
        } else {
            document.getElementById('no-session-view').style.display = 'block';
            document.getElementById('session-view').style.display = 'none';
            document.getElementById('close-session-btn').style.display = 'none';
        }

        refreshSessionsList(allSessions);
    }

    // Switch via selector
    function switchToSelectedSession() {
        const sessionId = document.getElementById('session-selector').value;
        if (sessionId) {
            selectSession(parseInt(sessionId));
        } else {
            selectSession(null);
        }
    }

    // Modal création session
    function showCreateSessionModal() {
        if (window.printSessionManager) {
            // Utiliser le modal global s'il existe
            const modal = document.getElementById('session-select-modal');
            if (modal) {
                document.getElementById('new-session-contact').value = '';
                document.getElementById('new-session-name').value = '';
                $(modal).modal('show');
                return;
            }
        }

        // Fallback: prompt simple avec notre nouveau système
        showAppModal({
            title: "Nouvelle Session",
            message: "Entrez le nom du contact:",
            prompt: true
        }, (contact) => {
            if (contact) {
                showAppModal({
                    title: "Nouvelle Session",
                    message: "Nom de la session (optionnel):",
                    prompt: true
                }, (sessionName) => {
                    createSession(contact, sessionName);
                });
            }
        });
    }

    // Créer session
    async function createSession(contact, sessionName) {
        if (window.printSessionManager) {
            await window.printSessionManager.createSession(contact, sessionName || '');
            await loadSessions();

            // Sélectionner la nouvelle session
            if (window.printSessionManager.currentSessionId) {
                selectSession(window.printSessionManager.currentSessionId);
            }
        }
    }

    // Charger jobs en attente (depuis print_jobs - table temporaire)
    let pendingJobs = [];

    async function loadPendingJobs() {
        try {
            const response = await fetch('?get_pending_jobs');
            const data = await response.json();
            pendingJobs = data.jobs || [];
            console.log('[AutoTirage] Jobs en attente chargés:', pending Jobs.length);
            updatePendingJobsDisplay();
        } catch (error) {
            console.error('[AutoTirage] Erreur chargement jobs en attente:', error);
        }
    }

    // Charger jobs de la session courante (depuis photocop/dupli)
    async function loadCurrentSessionJobs() {
        if (!currentSessionId) {
            sessionJobs = [];
            updateJobsDisplay();
            return;
        }

        try {
            // Charger jobs photocop + dupli avec session_id
            const response = await fetch(`?get_session_jobs&session_id=${currentSessionId}`);
            const data = await response.json();

            sessionJobs = data.jobs || [];
            updateJobsDisplay();
        } catch (error) {
            console.error('[AutoTirage] Erreur chargement jobs:', error);
        }
    }

    // Afficher jobs
    function updateJobsDisplay() {
        const tbody = document.getElementById('jobs-tbody');
        tbody.innerHTML = '';

        let total = 0;

        sessionJobs.forEach(job => {
            const row = document.createElement('tr');
            const price = parseFloat(job.prix || 0);
            total += price;

            row.innerHTML = `
            <td>${job.printerName || job.marque || 'N/A'}</td>
            <td><small>${job.document || job.nom || ''}</small></td>
            <td>${job.pages || job.nbCopies || 0}p x ${job.copies || 1}</td>
            <td>${(job.paper_cost || 0).toFixed(2)} €</td>
            <td>${(job.ink_cost || 0).toFixed(2)} €</td>
            <td><strong>${price.toFixed(2)} €</strong></td>
            <td>
                <button class="btn btn-danger btn-sm" onclick="deleteJob(${job.id}, '${job.table}')">
                    <i class="fa fa-trash"></i>
                </button>
            </td>
        `;

            tbody.appendChild(row);
        });

        document.getElementById('job-count').textContent = sessionJobs.length;
        document.getElementById('session-total').textContent = total.toFixed(2);
        document.getElementById('total-footer').textContent = total.toFixed(2);
    }

    // Fermer session
    async function closeCurrentSession() {
        if (!currentSessionId) return;

        showAppModal({
            message: 'Fermer cette session ?',
            confirm: true,
            type: 'warning'
        }, async (confirmed) => {
            if (!confirmed) return;

            if (window.printSessionManager) {
                await window.printSessionManager.closeSession(currentSessionId);
                currentSessionId = null;
                await loadSessions();
                selectSession(null);
            }
        });
    }

    // Terminer et fermer
    async function finishAndCloseSession() {
        if (!currentSessionId) return;

        showAppModal({
            message: `Valider ${sessionJobs.length} jobs et fermer la session ?`,
            confirm: true,
            type: 'success'
        }, async (confirmed) => {
            if (confirmed) {
                await closeCurrentSession();
            }
        });
    }

    // Supprimer job
    async function deleteJob(jobId, table) {
        showAppModal({
            message: 'Supprimer ce job ?',
            confirm: true,
            type: 'danger'
        }, async (confirmed) => {
            if (!confirmed) return;

            try {
                // TODO: API delete job
                console.log('Delete job', jobId, table);
                await loadCurrentSessionJobs();
            } catch (error) {
                console.error('Erreur suppression:', error);
            }
        }
</script>