<style>
    .main-container {
        background: white;
        border-radius: 15px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        margin: 1rem auto;
        overflow: hidden;
    }

    .header-section {
        background: linear-gradient(135deg, #e3f2fd 0%, #f3e5f5 100%);
        color: #424242;
        padding: 1.5rem;
        text-align: center;
        border-bottom: 1px solid #e0e0e0;
    }

    .header-section h1 {
        margin: 0;
        font-weight: 400;
        font-size: 2.2rem;
        color: #616161;
    }

    .form-section {
        padding: 1.5rem;
    }

    .btn-modern {
        border-radius: 10px;
        padding: 0.75rem 1.5rem;
        font-weight: 500;
        transition: all 0.3s ease;
    }

    .btn-primary-modern {
        background: linear-gradient(135deg, #81c784, #a5d6a7);
        border: none;
        color: white;
    }

    .btn-success-modern {
        background: linear-gradient(135deg, #a5d6a7, #c8e6c9);
        border: none;
        color: #2e7d32;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-xl-10">
            <div class="main-container">
                <div class="header-section">
                    <h1><i class="fa fa-magic"></i> Auto Tirage</h1>
                    <p>Impression automatique & Détection</p>
                </div>

                <div class="form-section">
                    <!-- Étape 1: Identification -->
                    <div id="step-identity" style="display:none;">
                        <div class="form-group text-center">
                            <label for="pseudo-input">
                                <h4>Qui êtes-vous ?</h4>
                            </label>
                            <input type="text" id="pseudo-input" class="form-control"
                                style="max-width:300px; margin:0 auto;" placeholder="Entrez un pseudo ou nom">
                            <button class="btn btn-primary-modern mt-3" onclick="startSession()">Démarrer la
                                session</button>
                        </div>
                    </div>

                    <!-- Étape 2: Écoute active -->
                    <div id="step-listening" style="display:none;">
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <div>
                                <h4>Session de : <span id="session-pseudo" class="text-primary"></span></h4>
                                <small class="text-muted">En attente d'impressions...</small>
                            </div>
                            <div class="spinner-grow text-success" role="status">
                                <span class="sr-only">Listening...</span>
                            </div>
                        </div>

                        <!-- Zone de logs / Status -->
                        <div id="activity-log" class="mb-4">
                            <!-- Les cartes de détection apparaîtront ici -->
                        </div>

                        <!-- Liste des jobs en attente de validation -->
                        <div id="pending-list-container" style="display:none;">
                            <h5 class="border-bottom pb-2 mb-3"><i class="fa fa-list"></i> Impressions en cours</h5>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Machine</th>
                                            <th>Document</th>
                                            <th>Détails</th>
                                            <th>Papier</th>
                                            <th>Encre</th>
                                            <th>Prix Total</th>
                                            <th>Papier Payé ?</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="pending-jobs-body">
                                        <!-- Rows generated by JS -->
                                    </tbody>
                                    <tfoot>
                                        <tr class="table-info">
                                            <td colspan="5" class="text-right"><strong>Total Session :</strong></td>
                                            <td colspan="3"><strong><span id="session-total">0.00</span> €</strong></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>

                            <div class="text-right mt-4">
                                <button class="btn btn-success-modern btn-lg" onclick="finishSession()">
                                    <i class="fa fa-check"></i> Terminer & Valider <span id="finish-badge"
                                        class="badge badge-light">0</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let sessionUser = "";
    let processedJobIds = new Set();
    let pendingJobs = new Map(); // For stabilization
    let sessionJobs = []; // List of validated jobs ready for checkout
    const STABILIZATION_DELAY = 10000;
    let lastCheckTime = Date.now();
    let pollingInterval = null;

    // Au chargement, vérifier s'il y a un pseudo dans l'URL ou localStorage
    document.addEventListener('DOMContentLoaded', () => {
        // Restaurer la session si elle existe
        const savedJobs = sessionStorage.getItem('auto_tirage_session_jobs');
        const savedUser = sessionStorage.getItem('auto_tirage_session_user');

        if (savedJobs && savedUser) {
            try {
                sessionJobs = JSON.parse(savedJobs);
                sessionUser = savedUser;

                // Restore processed IDs to enable live updates
                sessionJobs.forEach(job => {
                    if (job.originalJobId) processedJobIds.add(job.originalJobId);
                });

                document.getElementById('pseudo-input').value = sessionUser;
                document.getElementById('step-identity').style.display = 'none';
                document.getElementById('step-listening').style.display = 'block';
                document.getElementById('session-pseudo').textContent = sessionUser;
                renderSessionTable();
                startPolling();
                addLog('info', `✅ Session restaurée (${sessionJobs.length} jobs)`);
                return;
            } catch (e) {
                console.error('Erreur restauration session:', e);
            }
        }

        const urlParams = new URLSearchParams(window.location.search);
        const user = urlParams.get('user') || localStorage.getItem('auto_tirage_user');

        if (user) {
            document.getElementById('pseudo-input').value = user;
            startSession();
        } else {
            document.getElementById('step-identity').style.display = 'block';
        }
    });

    function startSession() {
        const pseudo = document.getElementById('pseudo-input').value.trim();
        if (!pseudo) return alert("Merci d'entrer un nom");

        sessionUser = pseudo;
        sessionStorage.setItem('auto_tirage_session_user', sessionUser);
        localStorage.setItem('auto_tirage_user', sessionUser);

        document.getElementById('step-identity').style.display = 'none';
        document.getElementById('step-listening').style.display = 'block';
        document.getElementById('session-pseudo').textContent = sessionUser;

        // Démarrer le polling
        startPolling();
    }

    function startPolling() {
        pollingInterval = setInterval(checkPrintJobs, 3000);
        addLog('info', "✅ Système prêt. Lancez une impression...");
    }

    async function checkPrintJobs() {
        try {
            const response = await fetch(`?check_print_jobs&after=${lastCheckTime}`);
            const data = await response.json();

            if (data.success && data.jobs && data.jobs.length > 0) {
                const newJobs = data.jobs.filter(job => {
                    const jobTime = new Date(job.timestamp).getTime();
                    if (jobTime > lastCheckTime && !processedJobIds.has(job.job_id)) {
                        return true;
                    }
                    return false;
                });

                newJobs.reverse().forEach(async (job) => {
                    handleJobCandidate(job);
                });
            }

            // Check for updates on ALREADY PROCESSED jobs (Live Update)
            if (data.jobs && data.jobs.length > 0) {
                data.jobs.forEach(job => {
                    if (processedJobIds.has(job.job_id)) {
                        checkForUpdate(job);
                    }
                });
            }

            processPendingJobs();

        } catch (error) {
            console.error("Erreur polling:", error);
        }
    }

    function handleJobCandidate(job) {
        if (processedJobIds.has(job.job_id)) return;

        const now = Date.now();
        if (!pendingJobs.has(job.job_id)) {
            pendingJobs.set(job.job_id, {
                job: job,
                firstSeen: now,
                lastUpdate: now
            });
            addLog('info', `⏳ Job détecté: ${job.document} (${job.total_pages} pages). Attente stabilisation (10s)...`);
        } else {
            const candidate = pendingJobs.get(job.job_id);
            if (candidate.job.total_pages !== job.total_pages || candidate.job.status !== job.status) {
                const oldPages = candidate.job.total_pages;
                candidate.job = job;
                candidate.lastUpdate = now;
                if (oldPages !== job.total_pages) {
                    addLog('info', `... maj pages : ${job.total_pages}`);
                }
            }
        }
    }

    function checkForUpdate(apiJob) {
        // Find in sessionJobs
        const existingIndex = sessionJobs.findIndex(j => j.originalJobId === apiJob.job_id);
        if (existingIndex === -1) return;

        const currentJob = sessionJobs[existingIndex];
        // Check if pages changed (e.g. 36 -> 108)
        // Note: simulation details uses 'pages' as 'pages per copy' in my previous hack, 
        // but let's compare with RAW total_pages from API.

        // We stored 'originalJobId' but not the raw total_pages in sessionJobs details...
        // But we can check if the new total_pages > calculated total stored?
        // Let's rely on apiJob.total_pages vs apiJob.timestamp

        // Simplest: If apiJob.total_pages > currentJob.total_pages_raw (we need to store this)
        if (apiJob.total_pages !== currentJob.raw_total_pages) {
            console.log(`Job ${apiJob.job_id} updated from ${currentJob.raw_total_pages} to ${apiJob.total_pages}`);
            simulateJob(apiJob, existingIndex); // Re-simulate and update in place
        }
    }

    function processPendingJobs() {
        const now = Date.now();
        pendingJobs.forEach(async (candidate, jobId) => {
            if (now - candidate.lastUpdate > STABILIZATION_DELAY) {
                pendingJobs.delete(jobId);
                processedJobIds.add(jobId);

                const t = new Date(candidate.job.timestamp).getTime();
                if (t > lastCheckTime) lastCheckTime = t;

                await simulateJob(candidate.job);
            }
        });
    }

    async function simulateJob(job, updateIndex = null) {
        addLog('process', `⚙️ Analyse du job : ${job.document}...`);

        try {
            // job.total_pages from DB is DOCUMENT pages (per copy)
            // We must multiply by copies to get global total, matching admin monitor logic.
            const copies = job.copies || 1;
            const pagesPerCopy = job.total_pages;
            const globalTotalPages = job.total_pages * copies;
            
            // Force robust boolean conversion for duplex
            const isDuplex = (job.duplex == 1 || job.duplex == '1' || job.duplex === true || String(job.duplex).toLowerCase() === 'oui');

            const payload = {
                printerName: job.printer_name,
                pages: pagesPerCopy,
                contact: sessionUser,
                document: job.document,
                copies: copies,
                total_pages: globalTotalPages,
                duplex: isDuplex,
                color_mode: job.color_mode,
                paper_size: job.paper_size,
                fill_rate: job.fill_rate || 0.5,
                timestamp: job.timestamp,
                simulate: true
            };

        // Pass the RAW total pages to the details for future comparison
        const rawTotalPages = job.total_pages;

        const response = await fetch('?save_auto_print', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        const result = await response.json();

        if (result.success) {
            // Store raw total pages for update checking
            result.details.raw_total_pages = job.total_pages;
            result.details.document_name = job.document;

            if (updateIndex !== undefined && updateIndex !== null) {
                addLog('info', `🔄 Mise à jour job : ${job.total_pages} pages`);
                updateJobInSession(result.details, updateIndex);
            } else {
                addLog('success', `✅ ${job.document} : ${result.details.price} €`);
                addJobToSession(result.details, job.job_id);
            }
        } else {
            addLog('error', `❌ Erreur: ${result.error}`);
        }

    } catch (error) {
        addLog('error', "❌ Erreur de communication serveur");
        console.error(error);
    }
    }

    function addJobToSession(details, jobId) {
        details.localId = Date.now() + Math.random().toString(36).substr(2, 9);
        details.originalJobId = jobId;
        details.feuilles_payees = false;

        sessionJobs.push(details);
        saveSession();
        renderSessionTable();
    }

    function updateJobInSession(newDetails, index) {
        // Keep some existing flags like localId or paid status if we want?
        // For now, reset but keep Id
        newDetails.localId = sessionJobs[index].localId;
        newDetails.originalJobId = sessionJobs[index].originalJobId;
        newDetails.feuilles_payees = sessionJobs[index].feuilles_payees; // Preserve paid status

        sessionJobs[index] = newDetails;
        saveSession();
        renderSessionTable();

        // Highlight effect
        const row = document.getElementById('pending-jobs-body').children[index];
        if (row) {
            row.style.backgroundColor = '#fff3cd';
            setTimeout(() => row.style.backgroundColor = '', 1000);
        }
    }

    function saveSession() {
        sessionStorage.setItem('auto_tirage_session_jobs', JSON.stringify(sessionJobs));
        sessionStorage.setItem('auto_tirage_session_user', sessionUser);
    }

    function renderSessionTable() {
        const container = document.getElementById('pending-list-container');
        const tbody = document.getElementById('pending-jobs-body');
        const totalSpan = document.getElementById('session-total');
        const badge = document.getElementById('finish-badge');

        container.style.display = 'block';
        tbody.innerHTML = '';

        let globalTotal = 0;

        sessionJobs.forEach((job, index) => {
            let currentPrice = job.price;
            if (job.feuilles_payees && job.cout_papier) {
                currentPrice = Math.max(0, currentPrice - job.cout_papier);
            }
            globalTotal += currentPrice;

            // Display like tirage_multimachines: X exemplaires × Y feuilles
            // nb_feuilles from backend is GLOBAL total sheets.
            // sheetsPerCopy = global sheets / copies
            const sheetsPerCopy = job.nb_feuilles ? Math.ceil(job.nb_feuilles / job.copies) : Math.ceil(job.pages / (job.duplex ? 2 : 1));
            const detailsText = job.type === 'photocop'
                ? `${job.copies} ex × ${sheetsPerCopy} feuilles<br><small>${job.duplex ? 'R/V' : 'Recto'} - ${job.taille}</small>`
                : `${job.nb_masters} M + ${job.nb_passages} P`;

            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><span class="badge badge-info">${job.machine}</span></td>
                <td><small>${job.document_name || '...'}</small></td>
                <td>${detailsText}</td>
                <td><small>${job.cout_papier ? job.cout_papier.toFixed(2) + ' €' : '-'}</small></td>
                <td><small>${job.cout_encre ? job.cout_encre.toFixed(2) + ' €' : (job.cout_masters ? (job.cout_masters + job.cout_passages).toFixed(2) + ' €' : '-')}</small></td>
                <td><strong>${currentPrice.toFixed(2)} €</strong></td>
                <td>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="paid-${index}" ${job.feuilles_payees ? 'checked' : ''} onchange="togglePaid(${index})">
                        <label class="custom-control-label" for="paid-${index}"></label>
                    </div>
                </td>
                <td>
                    <button class="btn btn-sm btn-danger" onclick="removeJob(${index})"><i class="fa fa-trash"></i></button>
                </td>
            `;
            tbody.appendChild(tr);
        });

        totalSpan.textContent = globalTotal.toFixed(2);
        badge.textContent = sessionJobs.length;
    }

    window.togglePaid = function (index) {
        sessionJobs[index].feuilles_payees = !sessionJobs[index].feuilles_payees;
        saveSession();
        renderSessionTable();
    };

    window.removeJob = function (index) {
        if (confirm('Supprimer ce job de la liste ?')) {
            sessionJobs.splice(index, 1);
            saveSession();
            renderSessionTable();
            if (sessionJobs.length === 0) {
                document.getElementById('pending-list-container').style.display = 'none';
                sessionStorage.removeItem('auto_tirage_session_jobs');
            }
        }
    };

    function addLog(type, message) {
        const logContainer = document.getElementById('activity-log');
        const div = document.createElement('div');
        const alertType = type === 'error' ? 'danger' : (type === 'success' ? 'success' : (type === 'process' ? 'warning' : 'info'));
        div.className = `alert alert-${alertType} py-2 mb-2`;

        const time = new Date().toLocaleTimeString();
        div.innerHTML = `<strong>[${time}]</strong> ${message}`;
        logContainer.prepend(div);

        if (logContainer.children.length > 8) {
            logContainer.lastChild.remove();
        }
    }

    window.finishSession = function () {
        if (sessionJobs.length === 0) return alert("Aucune impression à valider.");

        const form = document.createElement('form');
        form.method = 'POST';
        form.action = '?tirage_multimachines';

        addHidden(form, 'contact', sessionUser);
        addHidden(form, 'ok', '1');

        sessionJobs.forEach((job, index) => {
            addHidden(form, `machines[${index}][type]`, job.type === 'photocop' ? 'photocopieur' : 'duplicopieur');

            if (job.type === 'photocop') {
                addHidden(form, `machines[${index}][machine]`, job.machine);

                const bPrefix = `machines[${index}][brochures][0]`;
                // Use nb_feuilles from backend if available (handles duplex correctly), else fallback
                const sheetsPerCopy = job.nb_feuilles 
                    ? Math.ceil(job.nb_feuilles / job.copies) 
                    : Math.ceil((job.pages / job.copies) / (job.duplex ? 2 : 1));

                addHidden(form, `${bPrefix}[nb_exemplaires]`, job.copies);
                addHidden(form, `${bPrefix}[nb_feuilles]`, sheetsPerCopy);
                addHidden(form, `${bPrefix}[taille]`, job.taille);
                addHidden(form, `${bPrefix}[rv]`, job.duplex ? 'oui' : 'non');
                addHidden(form, `${bPrefix}[couleur]`, job.color ? 'oui' : 'non');
                addHidden(form, `${bPrefix}[feuilles_payees]`, job.feuilles_payees ? 'oui' : 'non');
            } else {
                addHidden(form, `machines[${index}][duplicopieur_id]`, job.machine_id);
                addHidden(form, `machines[${index}][nb_masters]`, job.nb_masters);
                addHidden(form, `machines[${index}][nb_passages]`, job.nb_passages);
                addHidden(form, `machines[${index}][rv]`, job.duplex ? 'oui' : 'non');
                addHidden(form, `machines[${index}][feuilles_payees]`, job.feuilles_payees ? 'oui' : 'non');
                addHidden(form, `machines[${index}][A4]`, job.taille === 'A4' ? 'A4' : 'A3');
                addHidden(form, `machines[${index}][tambour]`, 'tambour_noir');
            }
        });

        document.body.appendChild(form);
        // Clear session on submit to confirmation
        sessionStorage.removeItem('auto_tirage_session_jobs');
        sessionStorage.removeItem('auto_tirage_session_user');
        form.submit();
    };

    function addHidden(form, name, value) {
        const i = document.createElement('input');
        i.type = 'hidden';
        i.name = name;
        i.value = value;
        form.appendChild(i);
    }
</script>