name: Test Windows

on:
  push:
    branches:
      - feature/cross-platform-unification
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-windows:
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@27853eb8b46dc01c33bf9fef67d98df2683c3be2 # v2
        with:
          php-version: '8.2'
          extensions: sqlite3, pdo_sqlite, dom, curl, libxml, mbstring, zip
          tools: composer
          coverage: none

      - name: Install Node dependencies
        run: |
          npm config set msvs_version 2022
          $env:GYP_MSVS_VERSION="2022"
          npm install

      - name: Install PHP dependencies (Composer)
        working-directory: app
        run: composer install --optimize-autoloader --ignore-platform-reqs

      - name: Install system dependencies (Choco)
        run: |
          choco install ghostscript --version 10.6.0 -y --no-progress
          choco install imagemagick -y

      - name: Download Caddy
        run: |
          Invoke-WebRequest -Uri https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_windows_amd64.zip -OutFile caddy.zip
          Expand-Archive caddy.zip -DestinationPath caddy -Force
          del caddy.zip

      - name: Run PHP Tests (Pest)
        working-directory: app
        run: |
          $phpPath = (Get-Command php).Source
          $pestPath = "vendor\bin\pest.bat"
          & $phpPath $pestPath --group=unit --display-deprecations --display-errors

      - name: Run JS Tests (Jest)
        run: npm test -- --runInBand --forceExit